syntax = "proto3";
package streamerapi;
option go_package = "github.com/bloXroute-Labs/base-streamer/streamerapi";

import "protoc-gen-openapiv2/options/annotations.proto";
import "google/api/annotations.proto";

message IsHealthyRequest {
}

message IsHealthyResponse {
  uint64 block_number = 1;
}

message GetBdnBlockStreamRequest {
}

message GetBdnBlockStreamResponse {
  bytes block_header = 1;
  bytes block_body = 2;
}

message GetBdnFlashBlockStreamRequest {
}

message GetBdnFlashBlockStreamResponse {
  bytes bdn_flash_block = 1;
}

service Api {
  rpc IsHealthy(IsHealthyRequest) returns (IsHealthyResponse) {
    option (google.api.http) = {
      get: "/api/is_healthy"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      tags: "General";
    };
  }
  
  // Streams
  rpc GetBdnBlockStream(GetBdnBlockStreamRequest) returns (stream GetBdnBlockStreamResponse) {
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      tags: "Blockchain";
    };
  }

  rpc GetBdnFlashBlockStream(GetBdnFlashBlockStreamRequest) returns (stream GetBdnFlashBlockStreamResponse) {
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      tags: "Blockchain";
    };
  }
}