// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: streamer_api.proto

package streamerapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Api_IsHealthy_FullMethodName                    = "/streamerapi.Api/IsHealthy"
	Api_GetBdnBlockStream_FullMethodName            = "/streamerapi.Api/GetBdnBlockStream"
	Api_GetBdnFlashBlockStream_FullMethodName       = "/streamerapi.Api/GetBdnFlashBlockStream"
	Api_GetParsedBdnFlashBlockStream_FullMethodName = "/streamerapi.Api/GetParsedBdnFlashBlockStream"
)

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApiClient interface {
	IsHealthy(ctx context.Context, in *IsHealthyRequest, opts ...grpc.CallOption) (*IsHealthyResponse, error)
	// Streams
	GetBdnBlockStream(ctx context.Context, in *GetBdnBlockStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetBdnBlockStreamResponse], error)
	GetBdnFlashBlockStream(ctx context.Context, in *GetBdnFlashBlockStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetBdnFlashBlockStreamResponse], error)
	GetParsedBdnFlashBlockStream(ctx context.Context, in *GetParsedBdnFlashBlockStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetParsedBdnFlashBlockStreamResponse], error)
}

type apiClient struct {
	cc grpc.ClientConnInterface
}

func NewApiClient(cc grpc.ClientConnInterface) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) IsHealthy(ctx context.Context, in *IsHealthyRequest, opts ...grpc.CallOption) (*IsHealthyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsHealthyResponse)
	err := c.cc.Invoke(ctx, Api_IsHealthy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetBdnBlockStream(ctx context.Context, in *GetBdnBlockStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetBdnBlockStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Api_ServiceDesc.Streams[0], Api_GetBdnBlockStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetBdnBlockStreamRequest, GetBdnBlockStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Api_GetBdnBlockStreamClient = grpc.ServerStreamingClient[GetBdnBlockStreamResponse]

func (c *apiClient) GetBdnFlashBlockStream(ctx context.Context, in *GetBdnFlashBlockStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetBdnFlashBlockStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Api_ServiceDesc.Streams[1], Api_GetBdnFlashBlockStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetBdnFlashBlockStreamRequest, GetBdnFlashBlockStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Api_GetBdnFlashBlockStreamClient = grpc.ServerStreamingClient[GetBdnFlashBlockStreamResponse]

func (c *apiClient) GetParsedBdnFlashBlockStream(ctx context.Context, in *GetParsedBdnFlashBlockStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetParsedBdnFlashBlockStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Api_ServiceDesc.Streams[2], Api_GetParsedBdnFlashBlockStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetParsedBdnFlashBlockStreamRequest, GetParsedBdnFlashBlockStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Api_GetParsedBdnFlashBlockStreamClient = grpc.ServerStreamingClient[GetParsedBdnFlashBlockStreamResponse]

// ApiServer is the server API for Api service.
// All implementations must embed UnimplementedApiServer
// for forward compatibility.
type ApiServer interface {
	IsHealthy(context.Context, *IsHealthyRequest) (*IsHealthyResponse, error)
	// Streams
	GetBdnBlockStream(*GetBdnBlockStreamRequest, grpc.ServerStreamingServer[GetBdnBlockStreamResponse]) error
	GetBdnFlashBlockStream(*GetBdnFlashBlockStreamRequest, grpc.ServerStreamingServer[GetBdnFlashBlockStreamResponse]) error
	GetParsedBdnFlashBlockStream(*GetParsedBdnFlashBlockStreamRequest, grpc.ServerStreamingServer[GetParsedBdnFlashBlockStreamResponse]) error
	mustEmbedUnimplementedApiServer()
}

// UnimplementedApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApiServer struct{}

func (UnimplementedApiServer) IsHealthy(context.Context, *IsHealthyRequest) (*IsHealthyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsHealthy not implemented")
}
func (UnimplementedApiServer) GetBdnBlockStream(*GetBdnBlockStreamRequest, grpc.ServerStreamingServer[GetBdnBlockStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetBdnBlockStream not implemented")
}
func (UnimplementedApiServer) GetBdnFlashBlockStream(*GetBdnFlashBlockStreamRequest, grpc.ServerStreamingServer[GetBdnFlashBlockStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetBdnFlashBlockStream not implemented")
}
func (UnimplementedApiServer) GetParsedBdnFlashBlockStream(*GetParsedBdnFlashBlockStreamRequest, grpc.ServerStreamingServer[GetParsedBdnFlashBlockStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetParsedBdnFlashBlockStream not implemented")
}
func (UnimplementedApiServer) mustEmbedUnimplementedApiServer() {}
func (UnimplementedApiServer) testEmbeddedByValue()             {}

// UnsafeApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiServer will
// result in compilation errors.
type UnsafeApiServer interface {
	mustEmbedUnimplementedApiServer()
}

func RegisterApiServer(s grpc.ServiceRegistrar, srv ApiServer) {
	// If the following call pancis, it indicates UnimplementedApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Api_ServiceDesc, srv)
}

func _Api_IsHealthy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsHealthyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).IsHealthy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_IsHealthy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).IsHealthy(ctx, req.(*IsHealthyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetBdnBlockStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetBdnBlockStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApiServer).GetBdnBlockStream(m, &grpc.GenericServerStream[GetBdnBlockStreamRequest, GetBdnBlockStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Api_GetBdnBlockStreamServer = grpc.ServerStreamingServer[GetBdnBlockStreamResponse]

func _Api_GetBdnFlashBlockStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetBdnFlashBlockStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApiServer).GetBdnFlashBlockStream(m, &grpc.GenericServerStream[GetBdnFlashBlockStreamRequest, GetBdnFlashBlockStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Api_GetBdnFlashBlockStreamServer = grpc.ServerStreamingServer[GetBdnFlashBlockStreamResponse]

func _Api_GetParsedBdnFlashBlockStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetParsedBdnFlashBlockStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApiServer).GetParsedBdnFlashBlockStream(m, &grpc.GenericServerStream[GetParsedBdnFlashBlockStreamRequest, GetParsedBdnFlashBlockStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Api_GetParsedBdnFlashBlockStreamServer = grpc.ServerStreamingServer[GetParsedBdnFlashBlockStreamResponse]

// Api_ServiceDesc is the grpc.ServiceDesc for Api service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Api_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "streamerapi.Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsHealthy",
			Handler:    _Api_IsHealthy_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetBdnBlockStream",
			Handler:       _Api_GetBdnBlockStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetBdnFlashBlockStream",
			Handler:       _Api_GetBdnFlashBlockStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetParsedBdnFlashBlockStream",
			Handler:       _Api_GetParsedBdnFlashBlockStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "streamer_api.proto",
}
